SWYP-3rd-muud/muud-backend

.github/workflows/gradle.yml

feature: CD workflow 추가 #2

---

.github/workflows/gradle.yml
Dockerfile
src/main/resources/application.yml

- .gitignore 방식에서 github secrets 방식으로 변경

fix: property 저장 방식 변경

---

.github/workflows/gradle.yml
build.gradle
src/main/java/com/muud/testpackage/FileController.java
src/main/java/com/muud/testpackage/S3UploaderService.java
src/main/resources/application.yml

AWS S3를 파일 저장소로 사용합니다
- S3 연동
- 테스트용 업로드 컨트롤러 구현
- S3 정보들 secrets에 추가
- 스프링에 전달하는 workflow 추가
#12

feature: S3 연동 #12

---

src/main/java/com/muud/emotion/controller/EmotionController.java
src/main/java/com/muud/emotion/dto/EmotionResponse.java
src/main/java/com/muud/emotion/entity/Emotion.java
src/main/java/com/muud/emotion/service/EmotionService.java
src/test/java/com/muud/emotion/service/EmotionServiceTest.java

- Emotion enum 생성
- 감정 단일 조회 기능 구현
- 감정 전체 조회 기능 구현
- enum 값 추가
#15

감정 조회 기능 구현 #15

---

src/main/java/com/muud/config/WebConfig.java

전역 config을 추가했습니다
WebMVCConfigurer를 구현하여 전역 config 설정
#18

feature: CORS 이슈 해결을 위한 config 추가 #18

---

src/main/java/com/muud/global/auth/controller/AuthController.java
src/main/java/com/muud/global/auth/jwt/JwtInterceptor.java
src/main/java/com/muud/global/auth/jwt/JwtToken.java
src/main/java/com/muud/global/auth/jwt/JwtTokenUtils.java
src/main/java/com/muud/global/auth/service/AuthService.java
src/main/java/com/muud/global/config/WebConfig.java
src/main/java/com/muud/user/dto/UserInfo.java
src/main/java/com/muud/user/entity/LoginType.java
src/main/java/com/muud/user/entity/User.java
src/main/java/com/muud/user/repository/UserRepository.java
src/main/java/com/muud/user/service/UserService.java
src/main/resources/application.yml
src/main/resources/authprops.yml

jwt token 발급을 위한 모듈과 설정 파일을 추가함
-인증 관련 부분 authprops.yml 파일로 분리
-빌드 파일에 jwt 관련 모듈 추가
#16

chore: jwt token 모듈, 설정 파일 추가 #16

---

src/main/java/com/muud/auth/jwt/JwtInterceptor.java
src/main/java/com/muud/auth/jwt/JwtToken.java
src/main/java/com/muud/auth/jwt/JwtTokenUtils.java

토큰을 발급하고 유효성 검사를 하는 로직 추가
-JwtUtility Class 추가
-Interceptor Class 추가
#16

feature: JWT 토큰 발급 및 인증 로직 추가

---

src/main/java/com/muud/global/config/WebConfig.java

api 접근 전 Jwt 검증을 위한 Interceptor 등록
-WebConfig 파일 추가
#16

Feature: JwtInterceptor 등록 #16

---

src/main/java/com/muud/MuudApplication.java
src/main/java/com/muud/global/common/BaseEntity.java

Entity에서 공통으로 사용할 생성일자, 수정일자 필드를 포함한 BaseEntity 추가
-BaseEntity 추가
-Application Class에 @JpaAuditing 추가
#24

feature: BaseEntity 추가 #24

---

src/main/java/com/muud/diary/application/DiaryService.java
src/main/java/com/muud/diary/domain/Diary.java
src/main/java/com/muud/diary/dto/DiaryRequest.java
src/main/java/com/muud/diary/presentation/DiaryController.java
src/main/java/com/muud/diary/repository/DiaryRepository.java

일기 작성 기능 구현
- diary 패키지 추가
- 일기 작성 기능 구현
#26

feature: 일기 작성 기능 구현 #26

---

build.gradle
src/main/java/com/muud/diary/dto/DiaryRequest.java
src/main/java/com/muud/diary/presentation/DiaryController.java
src/main/java/com/muud/global/error/ExceptionType.java
src/main/java/com/muud/global/error/GlobalExceptionHandler.java
src/main/java/com/muud/global/error/ResponseError.java

유효성 검증 어노테이션 추가, 예외 처리
- 의존성 추가
- 예외처리
- 일기 내용 글자 제한 추가 (테스트용)
#33

유효성 검증 어노테이션 추가, 예외 처리

---

src/main/java/com/muud/diary/application/DiaryService.java
src/main/java/com/muud/diary/dto/DiaryResponse.java
src/main/java/com/muud/diary/presentation/DiaryController.java
src/main/java/com/muud/emotion/entity/Emotion.java

일기 단일 조회 기능 구현
- DiaryResponse 추가
- 컨트롤러, 서비스 구현
- enum 객체 리턴을 위한 JsonFormat 어노테이션 추가
#37

feature: 일기 단일 조회 기능 구현 #37

---

src/main/java/com/muud/diary/dto/DiaryResponse.java

fix: BaseEntity 수정 대응 #37

---

build.gradle
src/main/java/com/muud/auth/controller/AuthController.java
src/main/java/com/muud/auth/dto/SigninRequest.java
src/main/java/com/muud/auth/dto/SigninResponse.java
src/main/java/com/muud/auth/dto/SignupRequest.java
src/main/java/com/muud/auth/jwt/JwtInterceptor.java
src/main/java/com/muud/auth/jwt/JwtToken.java
src/main/java/com/muud/auth/jwt/JwtTokenUtils.java
src/main/java/com/muud/auth/service/AuthService.java
src/main/java/com/muud/auth/service/PasswordEncoder.java
src/main/java/com/muud/global/error/ExceptionType.java
src/main/java/com/muud/user/dto/UserInfo.java
src/main/java/com/muud/user/entity/User.java

-Jwt 모듈 및 클래스 추가
-이메일 회원가입 API 구현
-이메일 로그인 API 구현
-AuthController, AuthService, PasswordEncoder 추가
-Auth 관련 dto 추가
-JwtToken 관리 클래스 추가
#16

Feature: 이메일 회원가입,  Jwt 로그인 API 구현 #16 

---

src/main/java/com/muud/emotion/controller/EmotionController.java
src/main/java/com/muud/emotion/dto/EmotionResponse.java
src/main/java/com/muud/emotion/entity/Emotion.java
src/main/java/com/muud/emotion/service/EmotionService.java

대표 감정 개수 변경에 따른 수정
- 대표 감정 문자열 타입으로 변경
- 대표 감정 변수명 명확하게 변경
#44

fix: 대표 감정 개수 수정 #44

---

src/main/java/com/muud/diary/dto/DiaryResponse.java

누락건 변수명 수정
- fix: DiaryResponse 변수명 수정 #46
#46

fix: DiaryResponse 변수명 수정 #46

---

src/main/java/com/muud/diary/application/DiaryService.java
src/main/java/com/muud/diary/presentation/DiaryController.java
src/main/java/com/muud/diary/repository/DiaryRepository.java

`홈 화면`에 들어갈 월별 일기 조회 기능
feature: 월별 일기 조회 기능 구현 #39
#39

feature: 월별 일기 조회 기능 구현 #39

---

.github/workflows/gradle.yml
build.gradle
src/main/java/com/muud/auth/controller/AuthController.java
src/main/java/com/muud/auth/dto/KakaoInfoResponse.java
src/main/java/com/muud/auth/error/UserNotFoundException.java
src/main/java/com/muud/auth/service/AuthService.java
src/main/java/com/muud/auth/service/KakaoService.java
src/main/java/com/muud/global/error/ExceptionType.java

카카오 로그인 및 회원가입 기능 추가
-환경 변수 추가
-KakaoService 및 dto 추가
-API 구현
#14

feauture: 카카오 로그인 및 회원가입 기능 추가 #14

---

src/main/java/com/muud/diary/application/DiaryService.java
src/main/java/com/muud/diary/domain/Diary.java
src/main/java/com/muud/diary/presentation/DiaryController.java

일기 내용 수정 기능
feature: 일기 수정 기능 구현 #57
#57

feature: 일기 수정 기능 구현 #57

---

src/main/java/com/muud/auth/controller/AuthController.java
src/main/java/com/muud/auth/dto/SigninRequest.java
src/main/java/com/muud/auth/dto/SignupRequest.java
src/main/java/com/muud/user/controller/UserController.java
src/main/java/com/muud/user/entity/User.java
src/main/java/com/muud/user/repository/UserRepository.java
src/main/java/com/muud/user/service/UserService.java

User 닉네임 수정 기능 추가 및 로그인, 회원가입 검증 로직 추가
-UserService, User에 닉네임 추가 로직 구현
-UserController 추가
-Dto에 Validation 추가, Controller에 검증 추가
#14

feature: User 닉네임 수정 기능 추가 및 로그인, 회원가입 검증 로직 추가 #14

---

src/main/java/com/muud/auth/controller/AuthController.java
src/main/java/com/muud/auth/jwt/JwtInterceptor.java
src/main/java/com/muud/auth/jwt/JwtTokenUtils.java
src/main/java/com/muud/auth/service/AuthService.java
src/main/java/com/muud/auth/service/KakaoService.java
src/main/java/com/muud/global/config/WebConfig.java
src/main/java/com/muud/global/error/ExceptionType.java
src/main/java/com/muud/user/repository/UserRepository.java

JWT 검증 로직 
-JWTInterceptor 검증 로직 구체화
#53

feature: jwt 토큰 검증 로직 추가 #53

---

src/main/java/com/muud/bookmark/application/BookmarkService.java
src/main/java/com/muud/bookmark/domain/Bookmark.java
src/main/java/com/muud/bookmark/domain/dto/BookmarkRequest.java
src/main/java/com/muud/bookmark/domain/dto/BookmarkResponse.java
src/main/java/com/muud/bookmark/domain/repository/BookmarkRepository.java
src/main/java/com/muud/bookmark/presentation/BookmarkController.java
src/main/java/com/muud/diary/domain/Diary.java
src/main/java/com/muud/diary/dto/DiaryResponse.java
src/main/java/com/muud/diary/presentation/DiaryController.java

책갈피 기능 구현
- 책갈피 등록 기능
- 책갈피 취소 기능
- 북마크 조회 기능
- 유저별 북마크 조회 기능
#56

책갈피 기능 구현 #56

---

src/main/java/com/muud/playlist/dto/PlayListResponse.java
src/main/java/com/muud/playlist/entity/PlayList.java
src/main/java/com/muud/playlist/service/YoutubeDataService.java

Tag가 없는 PlayList에서 String 변환 시 발생하는 오류 해결
-없으면 respnose로 빈 리스트 반환하도록 변경
#54

fix: Tag 없음 오류 수정 #54

---

src/main/java/com/muud/diary/application/DiaryService.java
src/main/java/com/muud/diary/presentation/DiaryController.java
src/main/java/com/muud/emotion/controller/EmotionController.java
src/main/java/com/muud/emotion/dto/EmotionCountResponse.java
src/main/java/com/muud/emotion/service/EmotionService.java

감정 개수 조회 기능
- 일기 모두 불러오는 메소드 추가
- 감정 개수 조회 기능 구현
- 월별 게시글 조회 기능 엔드포인트 변경
#49

Feature/#49 감정 개수 조회 기능

---

src/main/java/com/muud/playlist/service/YoutubeDataService.java

fix: PlayList 초기화 방식 임시 수정 #54

---

src/main/java/com/muud/global/config/WebConfig.java

JwtInteceptor 예외 패턴에 카카오 로그인 추가
/auth/kakao/signin를 예외 패턴으로 추가함
#53

fix: 예외 패턴에 카카오 로그인 추가

---

src/main/java/com/muud/auth/jwt/JwtInterceptor.java

interceptor cors 우회 코드 변경
JwtInterceptor에 cors 우회 코드 변경

fix: interceptor cors 우회 코드 변경

---

src/main/java/com/muud/emotion/entity/Emotion.java

fix: emotion enum 값 변경
enumName, description 변경
#74

fix: emotion enum 값 변경 #74

---

src/main/java/com/muud/emotion/controller/EmotionController.java
src/main/java/com/muud/emotion/dto/QuestionResponse.java
src/main/java/com/muud/emotion/entity/Emotion.java
src/main/java/com/muud/emotion/service/EmotionService.java

feature: 감정 테스트 질문 조회 기능 구현
- Emotion enum에 question 필드 추가
- 서비스 메서드 구현
- 컨트롤러 메서드 구현
- Response 추가
#76

feature: 감정 테스트 질문 조회 기능 구현 #76

---

src/main/java/com/muud/diary/application/DiaryService.java
src/main/java/com/muud/diary/dto/DiaryPreviewResponse.java
src/main/java/com/muud/diary/presentation/DiaryController.java
src/main/java/com/muud/diary/repository/DiaryRepository.java

감정별 일기 미리보기 기능 구현
- 미리보기 기능 구현
- dto 추가
#38

feature: 감정별 일기 미리보기 기능 구현 #38

---

src/main/java/com/muud/playlist/controller/PlayListController.java
src/main/java/com/muud/playlist/service/YoutubeDataService.java

PlayList 데이터 업데이트 주기 변경
성능을 고려하여 API로 데이터 호출하는 부분을 매주 1회로 변경

fix: Playlist 데이터 업데이트 주기 변경

---

src/main/java/com/muud/collection/controller/CollectionController.java
src/main/java/com/muud/collection/dto/CollectionDto.java
src/main/java/com/muud/collection/entity/Collection.java
src/main/java/com/muud/collection/repositoty/CollectionRepository.java
src/main/java/com/muud/collection/service/CollectionService.java
src/main/java/com/muud/playlist/controller/PlayListController.java

collection 상세보기 기능 및 Collection PlayList 저장 방식 변경
-Collection 상세보기 로직 추가
-PlayList 대신 VideoId String 타입으로 변경
#77

feature: collection 상세보기 기능 #77

---

src/main/java/com/muud/playlist/repository/PlayListRepository.java
src/main/java/com/muud/playlist/service/PlayListService.java

collection 상세 조회 기능 추가
PlayList videoId로 조회하는 로직 추가
#77

feature: Collection 상세 조회 기능 #77

---

src/main/java/com/muud/collection/controller/CollectionController.java
src/main/java/com/muud/collection/service/CollectionService.java
src/main/java/com/muud/playlist/entity/PlayList.java
src/main/java/com/muud/playlist/service/YoutubeDataService.java

중복된 PlayList 문제 해결 
-PlayList에 Video ID unique로 변경
-API 호출시 필터 로직 수정
#77 #54

fix: 중복된 PlayList 제거

---

src/main/java/com/muud/collection/controller/CollectionController.java
src/main/java/com/muud/collection/dto/CollectionDto.java
src/main/java/com/muud/collection/entity/Collection.java
src/main/java/com/muud/collection/repository/CollectionRepository.java
src/main/java/com/muud/collection/service/CollectionService.java

Collection 좋아요/좋아요 취소 API 구현
-Collection 좋아요/좋아요 취소 API 구현 -> Patch로 묶음
-Collection Service에서 DTO로 반환하도록 수정
-Collection 가져와 User 확인하는 로직 별도의 함수로 관리
#77

feature: Collection 좋아요 기능 추가 #77

---

src/main/java/com/muud/collection/controller/CollectionController.java
src/main/java/com/muud/collection/repository/CollectionRepository.java
src/main/java/com/muud/collection/service/CollectionService.java

좋아요 누른 Collection 리스트 가져오는 API 구현
-좋아요 누른 Collection 리스트 가져오는 API 구현
-Controller, Service, Repository에 로직 추가

feature: 좋아요한  Collection 리스트 가져오기 #77

---

src/main/java/com/muud/diary/application/DiaryService.java
src/main/java/com/muud/diary/presentation/DiaryController.java
src/main/java/com/muud/diary/repository/DiaryRepository.java

fix: input date format 변경
- 월별 조회에서 연월별 조회 가능하도록 변경
#81

fix: input date format 변경 #81

---

src/main/java/com/muud/collection/controller/CollectionController.java
src/main/java/com/muud/collection/dto/CollectionDto.java
src/main/java/com/muud/collection/entity/Collection.java
src/main/java/com/muud/collection/repository/CollectionRepository.java
src/main/java/com/muud/collection/service/CollectionService.java
src/main/java/com/muud/playlist/entity/PlayList.java
src/main/java/com/muud/playlist/service/YoutubeDataService.java

PlayList 갱신 방식 변경
-삭제하지 않고 새롭게 추가하거나 업데이트 하는 방식으로 수정
-Collection에서 PlayList를 참조하도록 수정
#91

refactor: PlayList 갱신 방식 변경 #91

---

src/main/java/com/muud/playlist/service/YoutubeDataService.java

fix: PlayList 초기화 추가

---

src/main/java/com/muud/diary/presentation/DiaryController.java

fix: 일기 작성시 diaryId를 body에 포함하여 return #96
컨트롤러의 return값 수정 
#96

fix: 일기 작성시 diaryId를 body에 포함하여 return #96

---

src/main/java/com/muud/bookmark/domain/dto/BookmarkRequest.java
src/main/java/com/muud/bookmark/presentation/BookmarkController.java
src/main/java/com/muud/diary/application/DiaryService.java
src/main/java/com/muud/diary/repository/DiaryRepository.java
src/main/java/com/muud/emotion/controller/EmotionController.java

책갈피, 감정 로그인 정보 연동
- 책갈피와 로그인 유저 정보 연동
- 감정과 로그인 유저 정보 연동
#80

Fix/#80 로그인 정보를 책갈피, 감정 컨트롤러에 연동

---

src/main/java/com/muud/playlist/dto/PlayListRequest.java
src/main/java/com/muud/playlist/service/YoutubeDataService.java

데이터 세팅용 postconstruct 삭제
postconstruct 삭제

fix: postconstruct 삭제

---

src/main/java/com/muud/playlist/dto/PlayListRequest.java
src/main/java/com/muud/playlist/entity/PlayList.java
src/main/java/com/muud/playlist/service/YoutubeDataService.java

playlist 초기화 방식 수정
request로 추가할 수 있도록 수정
#91

fix: playlist 초기화 방식 수정 #91

---

src/main/java/com/muud/playlist/controller/PlayListController.java
src/main/java/com/muud/playlist/service/YoutubeDataService.java

playlist 초기 데이터 세팅 방식 api 호출로 수정 
-admin용 api 추가, code 방식으로 인증
-스캐줄 삭제
#104 #100

fix: playlist 초기 데이터 세팅 방식 api 호출로 수정 #104

---

.github/workflows/gradle.yml
src/main/resources/application.yml

관리자 인가용 코드 추가
-gradle.yml에 추가
-application.yml에 추가
#104

chore: 관리자용 code 추가 #104

---

.github/workflows/gradle.yml

fix: 변수 오타 수정 #104

---

.github/workflows/gradle.yml

feature: 컨테이너 중지 플로우에 조건문 추가 #82
- 컨테이너 실행 여부 확인 로직 추가
#82

feature: 컨테이너 중지 플로우에 조건문 추가 #82

---

.github/workflows/gradle.yml

fix: 오탈자 수정 #82

---

.github/workflows/gradle.yml

권한이 없어서 실행 안되는 문제 해결
fix: 데몬 권한 추가 
#82

fix: 데몬 권한 추가 #82

---

src/main/java/com/muud/global/util/PhotoS3Manager.java
src/main/resources/application.yml

fix: 로그 추가 #112

---

.github/workflows/gradle.yml

env 환경변수 경로 수정
fix: 환경변수 경로 수정 #112
#112

fix: 환경변수 경로 수정 #112

---

src/main/java/com/muud/global/util/PhotoS3Manager.java

버그 해결 완료로 인한 로그 제거
fix: 로그 제거 
#112

fix: 로그 제거 #112

---

src/main/java/com/muud/auth/controller/AuthController.java
src/main/java/com/muud/auth/dto/SignupRequest.java
src/main/java/com/muud/auth/jwt/Auth.java
src/main/java/com/muud/auth/jwt/JwtInterceptor.java
src/main/java/com/muud/auth/service/AuthService.java
src/main/java/com/muud/playlist/controller/PlayListController.java
src/main/java/com/muud/user/controller/UserController.java
src/main/java/com/muud/user/entity/Authority.java
src/main/java/com/muud/user/entity/User.java
src/main/resources/application.yml

User Authority 필드 추가
-User Authority 필드 추가
-Admin 계정 생성 로직 추가
-Admin 검증 로직 추가
#116

feature: User Authority 추가 #116

---

src/main/resources/application.yml

ddl 자동 생성 방식 변경
create -> none

fix: ddl 자동 생성 방식 변경

---

src/main/java/com/muud/auth/jwt/JwtInterceptor.java
src/main/java/com/muud/global/error/ExceptionType.java
src/main/java/com/muud/playlist/controller/PlayListController.java
src/main/java/com/muud/playlist/dto/PlayListRequest.java
src/main/java/com/muud/playlist/entity/PlayList.java
src/main/java/com/muud/playlist/service/PlayListService.java
src/main/java/com/muud/playlist/service/YoutubeDataService.java

Admin용 플레이리스트 추가, 삭제 API 추가
-PlayList 추가 API
-PlayList 삭제 API
#119

feature: PlayList 추가, 삭제 기능

---

src/main/java/com/muud/diary/application/DiaryService.java
src/main/java/com/muud/diary/domain/Diary.java
src/main/java/com/muud/diary/dto/DiaryRequest.java
src/main/java/com/muud/diary/dto/DiaryResponse.java

일기와 플리를 연동했습니다
- 엔티티 맵핑
- 요청, 응답 수정
#121

feature: 일기와 플리 연동 #121

---

src/main/java/com/muud/diary/application/DiaryService.java
src/main/java/com/muud/diary/dto/ContentUpdateRequest.java
src/main/java/com/muud/diary/presentation/DiaryController.java

fix: 일기 수정 기능 dto 변경
- 새로운 dto 추가
#123

fix: 일기 수정 기능 dto 변경 #123

---

src/main/java/com/muud/report/controller/ReportController.java
src/main/java/com/muud/report/dto/EmotionReport.java
src/main/java/com/muud/report/dto/PlaylistReport.java
src/main/java/com/muud/report/dto/RankDto.java
src/main/java/com/muud/report/dto/ReportResponse.java
src/main/java/com/muud/report/service/ReportService.java

월간 리포트 기능 구현
- dto 추가
- 기능 구현
#81

월간 리포트 기능 구현

---

src/main/java/com/muud/bookmark/controller/BookmarkController.java
src/main/java/com/muud/bookmark/service/BookmarkService.java
src/main/java/com/muud/diary/controller/DiaryController.java
src/main/java/com/muud/diary/domain/Diary.java
src/main/java/com/muud/diary/domain/dto/ContentUpdateRequest.java
src/main/java/com/muud/diary/domain/dto/DiaryPreviewResponse.java
src/main/java/com/muud/diary/domain/dto/DiaryRequest.java
src/main/java/com/muud/diary/domain/dto/DiaryResponse.java
src/main/java/com/muud/diary/repository/DiaryRepository.java
src/main/java/com/muud/diary/service/DiaryService.java
src/main/java/com/muud/emotion/controller/EmotionController.java
src/main/java/com/muud/emotion/domain/Emotion.java
src/main/java/com/muud/emotion/domain/dto/EmotionCountResponse.java
src/main/java/com/muud/emotion/domain/dto/EmotionResponse.java
src/main/java/com/muud/emotion/domain/dto/QuestionResponse.java
src/main/java/com/muud/emotion/service/EmotionService.java
src/main/java/com/muud/playlist/controller/PlayListController.java
src/main/java/com/muud/playlist/dto/PlayListRequest.java
src/main/java/com/muud/playlist/entity/PlayList.java
src/main/java/com/muud/playlist/repository/PlayListRepository.java
src/main/java/com/muud/playlist/service/PlayListService.java
src/main/java/com/muud/playlist/service/YoutubeDataService.java
src/main/java/com/muud/report/controller/ReportController.java
src/main/java/com/muud/report/domain/dto/EmotionReport.java
src/main/java/com/muud/report/domain/dto/PlaylistReport.java
src/main/java/com/muud/report/domain/dto/RankDto.java
src/main/java/com/muud/report/domain/dto/ReportResponse.java
src/main/java/com/muud/report/service/ReportService.java
src/test/java/com/muud/emotion/service/EmotionServiceTest.java

refactor: 패키지 구조 변경
패키지 구조 변경
#126

refactor: 패키지 구조 변경 #126

---

build.gradle

chore: health check를 위한 의존성 추가
라이브러리 추가
#128

chore: health check를 위한 의존성 추가

---

src/main/java/com/muud/global/config/WebConfig.java

프론트 배포 url로 변경
allowed origin 경로 변경

fix:allowed origin 수정

---

.github/workflows/gradle.yml
src/main/java/com/muud/global/config/WebConfig.java
src/main/resources/application.yml

fix: cors 문제 해결을 위한 설정 변경
origin 추가
#128

fix: cors 문제 해결을 위한 설정 변경

---

src/main/java/com/muud/diary/repository/DiaryRepository.java
src/main/java/com/muud/diary/service/DiaryService.java

일기 작성시 중복 검증하는 메서드 추가
중복 검증 메서드 추가
#134

일기 작성시 중복 검증하는 메서드 추가

---

src/main/java/com/muud/bookmark/controller/BookmarkController.java
src/main/java/com/muud/bookmark/repository/BookmarkRepository.java
src/main/java/com/muud/bookmark/service/BookmarkService.java

책갈피 1차 리팩터링
- fix: 패키지 구조 변경
- refactor: 메서드명 변경
- refactor: 파라미터에 final 추가하여 불변성 확보
#126

refactor: 책갈피 1차 리팩터링 

---

src/main/java/com/muud/auth/controller/AuthController.java
src/main/java/com/muud/auth/jwt/JwtInterceptor.java
src/main/java/com/muud/auth/jwt/JwtTokenUtils.java
src/main/java/com/muud/auth/service/AuthService.java
src/main/java/com/muud/user/controller/UserController.java
src/main/java/com/muud/user/entity/User.java

AccessToken 만료시 RefreshToken으로 갱신
-RefreshToken은 서버에서 쿠키에 세팅해주는 방식으로 구현
-AccessToken 갱신 엔드포인트 추가
#132

Feature: AccessToken 갱신 로직 추가 #132 

---

src/main/java/com/muud/auth/controller/AuthController.java
src/main/java/com/muud/auth/jwt/JwtTokenUtils.java
src/main/java/com/muud/auth/service/AuthService.java

토큰 파싱 복호화키 불일치 수정, Cookie 받아오는 방식 수정 
-Controller에서 CookieValue로 받아오게 수정
-Token 검증할 때 복호화키 불일치 수정
#139

fix: 복호화키 수정, Cookie 받아오는 방식 수정 #132

---

src/main/java/com/muud/auth/service/KakaoService.java
src/main/java/com/muud/global/error/ApiException.java
src/main/java/com/muud/global/error/GlobalExceptionHandler.java

클라이언트에서 kakao 로그인 에러 원인을 정확히 파악하기 위해 수정
kakao error message 추가

refactor: kakao login exception 처리 수정

---

src/main/java/com/muud/auth/service/KakaoService.java

카카오 서버에서 받은 exception 처리 로직 수정
-code가 안 왔을 때는 INVALID_INPUT으로 변경
-정확한 에러 메세지 반환(임시)

fix: exception 처리 로직 수정

---

src/main/java/com/muud/playlist/service/YoutubeDataService.java

플레이리스트 초기화 검색어 변경
-플레이리스트 감정별 검색어 변경
#54

refactor: 플리 검색어 변경

---

src/main/java/com/muud/diary/domain/dto/ContentUpdateRequest.java
src/main/java/com/muud/diary/domain/dto/DiaryRequest.java

일기 내용 글자 수 제한 변경
- request 수정
#146

fix: 일기 내용 글자 수 제한 변경 #146

---

build.gradle
src/main/resources/logback/Logback.xml

logback 설정 
- 의존성 추가
- xml 설정
#148

feature: logback 설정 #148

---

src/main/java/com/muud/collection/controller/CollectionController.java
src/main/java/com/muud/collection/domain/Collection.java
src/main/java/com/muud/collection/domain/dto/CollectionDto.java
src/main/java/com/muud/collection/repository/CollectionRepository.java
src/main/java/com/muud/collection/service/CollectionService.java
src/main/java/com/muud/user/entity/User.java

패키지 구조 수정, dto 타입 record로 수정
-CollectionDto 타입을 record로 수정 후 of, from으로 변경
-domain 밑으로 패키지 구조 변경
#154

refactor: 패키지 구조 수정, dto 타입 record로 수정 #154

---

README.md

Muud 서비스에 대한 README 추가
docs: 프로젝트 README 추가 
#156

docs: 프로젝트 README 추가 #156

---

build.gradle
src/main/java/com/muud/global/common/controller/StatusCheckController.java

보안이슈로 인해 actuator의 의존성을 제거하고 전용 컨트롤러 추가
- actuator 의존성 제거
- health-check controller 추가
#158

refactor: actuator 의존성 제거 #158

---

src/main/java/com/muud/diary/controller/DiaryController.java
src/main/java/com/muud/diary/domain/dto/DiaryRequest.java
src/main/java/com/muud/diary/service/DiaryService.java
src/main/java/com/muud/emotion/domain/Emotion.java

일기 작성시 클라이언트로 부터 입력받는 값들에 대한 검증 
feature: 감정 검증 메서드 추가
feature: 일기 작성 요청시 입력값 검증
fix: 일기 중복 작성시 예외 메세지 추가
#161

feature: 일기 작성시 입력값 검증 로직 구현

---

src/main/java/com/muud/bookmark/controller/BookmarkController.java
src/main/java/com/muud/bookmark/repository/BookmarkRepository.java
src/main/java/com/muud/bookmark/service/BookmarkService.java
src/main/java/com/muud/diary/controller/DiaryController.java
src/main/java/com/muud/diary/domain/dto/DiaryPreviewResponse.java
src/main/java/com/muud/diary/domain/dto/DiaryRequest.java
src/main/java/com/muud/diary/repository/DiaryRepository.java
src/main/java/com/muud/diary/service/DiaryService.java
src/main/java/com/muud/emotion/controller/EmotionController.java
src/main/java/com/muud/emotion/domain/Emotion.java
src/main/java/com/muud/emotion/domain/dto/EmotionResponse.java
src/main/java/com/muud/global/common/PageResponse.java
src/main/java/com/muud/global/config/WebConfig.java
src/main/java/com/muud/global/error/ApiException.java
src/main/java/com/muud/global/error/ExceptionType.java
src/main/java/com/muud/global/error/GlobalExceptionHandler.java
src/main/java/com/muud/global/error/ResponseError.java
src/main/java/com/muud/global/util/PhotoS3Manager.java
src/main/java/com/muud/report/controller/ReportController.java
src/main/java/com/muud/report/service/ReportService.java

가독성을 위한 코딩 컨벤션 통일 커밋
- 불필요한 주석 제거
- 수직 공백 추가
#160

refactor: 컨벤션 통일 #160

---

src/main/java/com/muud/auth/controller/AuthController.java
src/main/java/com/muud/auth/domain/dto/KakaoInfoResponse.java
src/main/java/com/muud/auth/domain/dto/SignupResponse.java
src/main/java/com/muud/auth/domain/dto/TokenResponse.java
src/main/java/com/muud/auth/jwt/JwtInterceptor.java
src/main/java/com/muud/auth/service/AuthService.java
src/main/java/com/muud/auth/service/KakaoService.java
src/main/java/com/muud/auth/service/PasswordEncoder.java

Auth 컨벤션 통일 및 코드 리팩토링
-컨벤션 통일
-SignupResponse, TokenResponse 생성, Map 삭제
-하드코딩 상수로 변경
#166

refactor: Auth 컨벤션 통일, 코드 리팩토링 #166

---

src/main/java/com/muud/auth/jwt/JwtTokenUtils.java
src/main/java/com/muud/auth/service/AuthService.java

createToken 함수 수정
-createToken() 함수 Date, 만료 기간 넘기는 방식으로 수정
-토큰 재발행 
#166

refactor: createToken 함수 수정

---

src/main/java/com/muud/MuudApplication.java
src/main/java/com/muud/diary/config/ImageDirectoryConfig.java
src/main/java/com/muud/diary/controller/DiaryController.java
src/main/java/com/muud/diary/domain/Diary.java
src/main/java/com/muud/diary/service/DiaryService.java
src/main/java/com/muud/emotion/controller/EmotionController.java

diary 리팩토링
- refactor: 일기 소유권 검증 메서드 통합
- refactor: user 파라미터 전달 방식 변경
- fix: 트랜잭션 어노테이션 분리
- refactor: diary 생성시 정적 팩토리 메서드 사용하도록 변경
- refactor: 환경변수 바인딩 방식 변경
#168

refactor: diary 리팩토링 #168

---

src/main/java/com/muud/auth/domain/dto/KakaoInfoResponse.java
src/main/java/com/muud/auth/domain/dto/SigninRequest.java
src/main/java/com/muud/auth/domain/dto/SigninResponse.java
src/main/java/com/muud/auth/domain/dto/SignupRequest.java
src/main/java/com/muud/auth/domain/dto/SignupResponse.java
src/main/java/com/muud/auth/jwt/JwtToken.java

Auth 패키지 DTO 컨벤션 통일
-record 타입 파라미터 2개 이상부터 개행
-클래스 선언과 함수 선언 사이 행 추가
#166

refactor: dto 컨벤션 통일 #166

---

src/main/java/com/muud/auth/controller/AuthController.java
src/main/java/com/muud/auth/service/KakaoService.java

AuthController, KakaoService 코드 리팩토링
-AuthController 메소드 RespnoseEntity<T> 타입 명시
-KakaoService의 getKakaoToken 반환 타입 Map에서 String으로 변경(refreshToken은 사용하지 않아 삭제함)
#166

refactor: AuthController, KakaoService 코드 리팩토링 #166

---

src/main/java/com/muud/auth/jwt/JwtTokenUtils.java
src/main/java/com/muud/auth/service/AuthService.java

변수 상수로 변경, 분리된 함수 합침
-토큰 타입 TOKEN_TYPE 상수 생성
-한곳에서만 호출되는 getUserById, getUserByEmail 함수 호출하는 함수에 합침
#166

refactor: 토큰 타입 변수 상수로 변경, 분리된 함수 합침 #166

---

src/main/java/com/muud/diary/controller/DiaryController.java
src/main/java/com/muud/diary/domain/dto/CreateDiaryResponse.java
src/main/java/com/muud/diary/service/DiaryService.java

서비스 계층 분리
- 컨트롤러와 서비스 레이어간의 역할 분리
- response 추가
#173

refactor: 서비스 계층 분리 #173

---

src/main/java/com/muud/auth/service/AuthService.java
src/main/java/com/muud/user/service/UserService.java

트랜잭션 읽기 전용 범위 수정
-AuthService, UserService 클래스 범위 readonly를 메소드 단위로 수정
#174

fix: 트랜잭션 읽기 전용 수정 #174

---

build.gradle
src/main/java/com/muud/diary/controller/DiaryController.java
src/main/java/com/muud/global/config/SwaggerConfig.java

api 명세, 테스트를 위한 스웨거 설정입니다
- 의존성 주입
- config 설정
- 샘플 작성
#179
{서버주소}:{포트}/swagger-ui/index.html 에 접속하면 api 목록을 확인할 수 있습니다.

feat: swagger 설정 #179
